# Global
[global.3rdLibraries]
linux = [
    {name = "raylib", url = "https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz"}
]
windows = []

[global.copySources]
linux = [
    {from = "3rd/raylib/lib/libraylib.so.550", to = "bin"},
    {from = "3rd/raylib/LICENSE", to = "lic/libraylib.so.550.LICENSE"}
]
windows = []

[global.flags]
shared = ["-std=c++23"]
compile = []
link = []

[global.debugOnlyFlags]
shared = []
compile = []
link = []

# Entry Build
[build.entry.flags]
shared = []
compile = []
link = []

[build.entry.debugOnlyFlags]
shared = []
compile = []
link = []

[build.entry.dynamicLibraries]
linux = [
    "libraylib.so.550"
]
windows = []

[build.entry]
binType = "executable"
binName = "app"
debugBinName = "app_d"
sources = [
    "main.cxx"
]