# Global
[global]
createDirectories = [
    "bin"
]

[global.flags]
shared = ["-std=c++23"]
compile = []
link = []

[global.debugOnlyFlags]
shared = []
compile = []
link = []

# Entry Build
[build.entry.flags]
shared = []
compile = []
link = []

[build.entry.debugOnlyFlags]
shared = []
compile = []
link = []

[build.entry]
binType = "executable"
binDir = "bin"
binName = "app"
debugBinName = "app_d"
sources = [
    "main.cxx",
    "hello/hello.cxx"
]